### ISSUE TITLE
Spawning doesnt work

### ISSUE THREAD

**Issue by DiskGG** [Softsplit/sandbox-plus-plus#16]
System.Exception: Can't run 'spawn'
   at Sandbox.ConsoleSystem.RunInternal(ConsoleCommand command)
   at Sandbox.ConsoleSystem.Run(String command, Object[] arguments)
   at ModelList.SpawnPackage(Package package) in LegacyUI/Left/ModelList.razor:line 54
   at PackageList.<>c__DisplayClass1_0.<BuildRenderTree>b__1() in LegacyUI/Components/PackageList.razor:line 11
   at PackageIcon.<BuildRenderTree>b__1_0() in LegacyUI/Components/PackageIcon.razor:line 7
   at Sandbox.UI.Panel.OnEvent(PanelEvent e)
   at Sandbox.UI.Panel.RunPendingEvents()

**Comment by Asphaltian** [comment]
Resolved with commit 525ffd1
